teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 7
      y: 6
    scale_linear:
      x: 1.0
      y: 1.0
    scale_linear_turbo:
      x: 1.5
      y: 1.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 0.4

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
